# Generated by Django 2.0.1 on 2019-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20190401_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'TODO'), ('prog', 'In Progress'), ('paus', 'Paused'), ('done', 'DONE')], max_length=4),
        ),
    ]
