# Generated by Django 2.0.1 on 2019-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_auto_20190421_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
